spring:
  rabbitmq:
    host: 172.16.85.128
    port: 5672
    username: admin
    password: admin
    virtual-host: my_vhost
    connection-timeout: 50000
    publisher-confirms: true #开启发送消息到exchange确认机制
    publisher-returns: true #开启发送消息到exchange但是exchange没有和队列绑定的确认机制
    listener:
      simple:
        auto-startup: true
        concurrency: 10   # 消费者最小数量
        default-requeue-rejected: true # 是否重新排队如果发送失败； 默认为“ true”。
        max-concurrency: 10  #最大消费者数。
        prefetch: 1
    template:
      retry:
        enabled: true  #开启重试机制
        initial-interval: 1000ms   #第一次和第二次尝试传递消息之间的间隔。
        max-attempts: 3   #重试次数
        max-interval: 10000ms  # 两次尝试之间的最大间隔。
        multiplier: 1.0  #下一个与前一个重试间隔的乘数。